select 'card_pack', count() from card_pack; --
select 'card_colors', count() from  card_colors; --
select 'types', count() from  types; --
select 'stats', count() from  stats; --
select 'moves', count() from  moves; --
select 'abilities', count() from  abilities; --
select 'pokemon', count() from  pokemon; --
select 'pokemon_stats', count() from  pokemon_stats; --
select 'egg_groups', count() from  egg_groups; --
select 'go_moves', count() from  go_moves; --
select 'exp_level_thresholds', count() from  exp_level_thresholds; --
select 'type_effectiveness', count() from  type_effectiveness; --
select 'status_effects', count() from  status_effects; --
select 'regions', count() from  regions; --
select 'generations', count() from  generations; --
select 'locations', count() from  locations; --
select 'items', count() from  items; --
select 'natures', count() from  natures; --
select 'languages', count() from  languages; --
select 'card_metadata', count() from  card_metadata; --
select 'trainer_cards', count() from  trainer_cards; --
select 'energy_cards', count() from  energy_cards; --
select 'energy_card_contents', count() from  energy_card_contents; --
select 'pokemon_cards', count() from  pokemon_cards; --
select 'retreat_cost', count() from  retreat_cost; --
select 'card_attacks', count() from  card_attacks; --
select 'card_attack_costs', count() from  card_attack_costs; --

---NOT IMPLEMENTED ANYWHERE
select 'pokemon_card_evolutions', count() from  pokemon_card_evolutions; --
select 'go_stats', count() from  go_stats; --
select 'pokemon_abilities', count() from  pokemon_abilities; --
select 'pokemon_moves', count() from  pokemon_moves; --
select 'pokemon_egg_groups', count() from  pokemon_egg_groups; --
select 'move_effects', count() from  move_effects; --
select 'type_immunity', count() from  type_immunity; --
select 'games', count() from  games; --
select 'starters', count() from  starters; --
select 'trainers', count() from  trainers; --
select 'catch_locations', count() from  catch_locations; --
select 'game_pokemon', count() from  game_pokemon; --
select 'trainer_teams', count() from  trainer_teams; --
select 'berry_locations', count() from  berry_locations; --
select 'berry_effects', count() from  berry_effects; --
select 'game_locations', count() from  game_locations; --
select 'game_items', count() from  game_items; --
select 'language_translations', count() from  language_translations; --
select 'move_translations', count() from  move_translations; --
select 'type_translations', count() from  type_translations; --
select 'ability_translations', count() from  ability_translations; --
select 'generation_translations', count() from  generation_translations; --
select 'region_translations', count() from  region_translations; --
select 'game_translations', count() from  game_translations; --
select 'item_translations', count() from  item_translations; --
select 'nature_translations', count() from  nature_translations; --
select 'location_translations', count() from  location_translations; --